{"name": "test_one", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <camp_study_interface.aek.testcase.test_login.TestLogin object at 0x000001E638085010>\n\n    def test_one(self):\n        print(\"hello\")\n        q=1\n        w=2\n>       assert  q==w\nE       assert 1 == 2\n\ntestcase\\test_login.py:28: AssertionError"}, "start": 1676208907138, "stop": 1676208907138, "uuid": "27be1554-9985-42d2-8238-5808ae151b07", "historyId": "493e688716a450cb9a514eb7ab3d4d94", "testCaseId": "984d53a885d679341cc871db781b79b9", "fullName": "testcase.test_login.TestLogin#test_one", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "我叫小白菜"}, {"name": "thread", "value": "17248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}